name: "Splunk Workflow Information"
description: "Action to pass information about GH workflow jobs results"
inputs:
  splunk_host:
    description: "Splunk host address"
    required: true
  splunk_token:
    description: "Splunk HEC token"
    required: true
  index:
    description: "Splunk index in which data will be stored"
    default: "main"
    required: false
  splunk_port:
    description: "Splunk HEC port"
    default: "8088"
    required: false
  splunk_hec_scheme:
    description: "protocol which will be used while sending data through HEC - http/https"
    default: "https"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
