# action.yml
name: "Splunk Workflow Information"
description: "Action to pass information about GH workflow jobs results"
inputs:
  repository:
    description: "github repository name"
    required: true
  run_id:
    description: "run id to fetch data"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"